### ISSUE TITLE
Legend improvments

### ISSUE THREAD

**Issue by timlinux** [landinfotech/mycivitas#116]
![image](https://user-images.githubusercontent.com/178003/125605027-f8643464-eccb-49e6-8648-09c623e1606e.png)

![image](https://user-images.githubusercontent.com/178003/125605144-a1a096ad-35b6-4826-9fba-cd768281af80.png)

@Andrevdb can we sit together and work to improve the legends?

**Comment by Andrevdb** [comment]
#155
