### ISSUE TITLE
Civitas Viewer - Features do not display

### ISSUE THREAD

**Issue by tjaartvdb** [landinfotech/mycivitas#230]
"Default" view for Street lamps do not display. But displays for "C", "P" and "R" views
![image](https://user-images.githubusercontent.com/71300724/135880449-f1e41b29-5592-4098-b034-5de0ecfd34b4.png)
![image](https://user-images.githubusercontent.com/71300724/135880529-30406e50-c280-4a95-a1ac-aed631806195.png)

**Comment by Andrevdb** [comment]
@tjaartvdb Can you check this? Zoom in to a higher level?

**Comment by tjaartvdb** [comment]
Ok thanks
