### ISSUE TITLE
Add tax rates Stripe

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/mycivitas#257]
In the EULA, we specify that tax rates are not included. Do we need to add these?

**Comment by Andrevdb** [comment]
Do we need to worry about this?

**Comment by Andrevdb** [comment]
@tjaartvdb @timlinux

**Comment by timlinux** [comment]
ok thanks, @meomancer will work on this next week

**Comment by meomancer** [comment]
It is not finished yet
PR : https://github.com/landinfotech/mycivitas/pull/280
